/*
  # Agency Structure: Multi-client management for admins

  Enables admins to manage multiple clients, with deployment tracking,
  test platform management, and reporting capabilities.

  New tables:
  - client_companies: Maps admin (company) to their client companies
  - deployment_platforms: Available platforms (iOS, Android, Web, etc)
  - deployments: Deployment records per client
  - test_platforms: Test services (TestFlight, TestFairy, etc)
  - test_builds: Test builds per client
  - reports: Reports generated by admins
  - developer_access_roles: Define which devs have cross-admin access
*/

-- ============================================================
-- CLIENT_COMPANIES (Admin → Client relationship)
-- ============================================================

CREATE TABLE IF NOT EXISTS client_companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  client_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  client_contact_name text NOT NULL DEFAULT '',
  client_contact_email text NOT NULL DEFAULT '',
  client_contact_phone text NOT NULL DEFAULT '',
  notes text DEFAULT '',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(admin_company_id, client_company_id)
);

CREATE INDEX IF NOT EXISTS idx_client_companies_admin ON client_companies(admin_company_id);
CREATE INDEX IF NOT EXISTS idx_client_companies_client ON client_companies(client_company_id);

ALTER TABLE client_companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "client_companies_admin_select"
  ON client_companies FOR SELECT TO authenticated
  USING (
    admin_company_id = get_my_company() AND get_my_role() = 'admin'
    OR client_company_id = get_my_company() AND get_my_role() IN ('admin','agent','developer')
    OR get_my_role() = 'superadmin'
  );

CREATE POLICY "client_companies_admin_insert"
  ON client_companies FOR INSERT TO authenticated
  WITH CHECK (admin_company_id = get_my_company() AND get_my_role() = 'admin');

CREATE POLICY "client_companies_admin_update"
  ON client_companies FOR UPDATE TO authenticated
  USING (admin_company_id = get_my_company() AND get_my_role() = 'admin')
  WITH CHECK (admin_company_id = get_my_company() AND get_my_role() = 'admin');

CREATE POLICY "client_companies_admin_delete"
  ON client_companies FOR DELETE TO authenticated
  USING (admin_company_id = get_my_company() AND get_my_role() = 'admin');

-- ============================================================
-- DEPLOYMENT_PLATFORMS
-- ============================================================

CREATE TABLE IF NOT EXISTS deployment_platforms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text DEFAULT '',
  icon text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

INSERT INTO deployment_platforms (name, description) VALUES
  ('iOS - App Store', 'Apple App Store'),
  ('Android - Google Play', 'Google Play Store'),
  ('Web', 'Web application'),
  ('Web - PWA', 'Progressive Web App'),
  ('macOS - App Store', 'macOS App Store'),
  ('Windows', 'Windows application'),
  ('Linux', 'Linux application')
ON CONFLICT DO NOTHING;

ALTER TABLE deployment_platforms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deployment_platforms_select"
  ON deployment_platforms FOR SELECT TO authenticated
  USING (is_active = true OR get_my_role() = 'superadmin');

-- ============================================================
-- DEPLOYMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS deployments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  platform_id uuid NOT NULL REFERENCES deployment_platforms(id),
  version text NOT NULL,
  build_number text NOT NULL,
  release_notes text DEFAULT '',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'in_review', 'approved', 'rejected', 'live', 'rollback')),
  submitted_by uuid REFERENCES profiles(id),
  submitted_at timestamptz,
  approved_by uuid REFERENCES profiles(id),
  approved_at timestamptz,
  live_at timestamptz,
  rollback_at timestamptz,
  rollback_reason text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deployments_client ON deployments(client_company_id);
CREATE INDEX IF NOT EXISTS idx_deployments_platform ON deployments(platform_id);
CREATE INDEX IF NOT EXISTS idx_deployments_status ON deployments(status);
CREATE INDEX IF NOT EXISTS idx_deployments_created ON deployments(created_at);

ALTER TABLE deployments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deployments_admin_select"
  ON deployments FOR SELECT TO authenticated
  USING (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company() AND get_my_role() = 'admin'
    ))
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','agent','developer'))
    OR get_my_role() = 'superadmin'
  );

CREATE POLICY "deployments_dev_insert"
  ON deployments FOR INSERT TO authenticated
  WITH CHECK (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  );

CREATE POLICY "deployments_dev_update"
  ON deployments FOR UPDATE TO authenticated
  USING (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  )
  WITH CHECK (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  );

-- ============================================================
-- TEST_PLATFORMS
-- ============================================================

CREATE TABLE IF NOT EXISTS test_platforms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text DEFAULT '',
  icon text DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

INSERT INTO test_platforms (name, description) VALUES
  ('TestFlight', 'Apple TestFlight for iOS'),
  ('TestFairy', 'TestFairy for mobile testing'),
  ('Firebase Test Lab', 'Google Firebase Test Lab for Android'),
  ('Appetize', 'Cloud-based mobile app testing'),
  ('BrowserStack', 'Cloud browser and device testing'),
  ('Internal Testing', 'Internal QA testing')
ON CONFLICT DO NOTHING;

ALTER TABLE test_platforms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "test_platforms_select"
  ON test_platforms FOR SELECT TO authenticated
  USING (is_active = true OR get_my_role() = 'superadmin');

-- ============================================================
-- TEST_BUILDS
-- ============================================================

CREATE TABLE IF NOT EXISTS test_builds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  platform_id uuid NOT NULL REFERENCES test_platforms(id),
  version text NOT NULL,
  build_number text NOT NULL,
  test_url text DEFAULT '',
  build_file_url text DEFAULT '',
  test_notes text DEFAULT '',
  status text NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'distributed', 'testing', 'completed', 'failed', 'archived')),
  uploaded_by uuid REFERENCES profiles(id),
  uploaded_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_test_builds_client ON test_builds(client_company_id);
CREATE INDEX IF NOT EXISTS idx_test_builds_platform ON test_builds(platform_id);
CREATE INDEX IF NOT EXISTS idx_test_builds_status ON test_builds(status);

ALTER TABLE test_builds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "test_builds_admin_select"
  ON test_builds FOR SELECT TO authenticated
  USING (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company() AND get_my_role() = 'admin'
    ))
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','agent','developer'))
    OR get_my_role() = 'superadmin'
  );

CREATE POLICY "test_builds_dev_insert"
  ON test_builds FOR INSERT TO authenticated
  WITH CHECK (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  );

CREATE POLICY "test_builds_dev_update"
  ON test_builds FOR UPDATE TO authenticated
  USING (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  )
  WITH CHECK (
    (client_company_id IN (
      SELECT client_company_id FROM client_companies
      WHERE admin_company_id = get_my_company()
    ) AND get_my_role() = 'developer')
    OR (client_company_id = get_my_company() AND get_my_role() IN ('admin','developer'))
  );

-- ============================================================
-- REPORTS
-- ============================================================

CREATE TABLE IF NOT EXISTS reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  client_company_id uuid REFERENCES companies(id) ON DELETE CASCADE,
  title text NOT NULL,
  report_type text NOT NULL CHECK (report_type IN ('tickets', 'deployments', 'testing', 'combined', 'custom')),
  period_start date NOT NULL,
  period_end date NOT NULL,
  data jsonb DEFAULT '{}',
  generated_by uuid NOT NULL REFERENCES profiles(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reports_admin ON reports(admin_company_id);
CREATE INDEX IF NOT EXISTS idx_reports_client ON reports(client_company_id);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "reports_admin_select"
  ON reports FOR SELECT TO authenticated
  USING (
    admin_company_id = get_my_company() AND get_my_role() = 'admin'
    OR get_my_role() = 'superadmin'
  );

CREATE POLICY "reports_admin_insert"
  ON reports FOR INSERT TO authenticated
  WITH CHECK (admin_company_id = get_my_company() AND get_my_role() = 'admin');

CREATE POLICY "reports_admin_update"
  ON reports FOR UPDATE TO authenticated
  USING (admin_company_id = get_my_company() AND get_my_role() = 'admin')
  WITH CHECK (admin_company_id = get_my_company() AND get_my_role() = 'admin');

CREATE POLICY "reports_admin_delete"
  ON reports FOR DELETE TO authenticated
  USING (admin_company_id = get_my_company() AND get_my_role() = 'admin');

-- ============================================================
-- Update tickets RLS to support developers across admins
-- ============================================================

CREATE POLICY "tickets_developer_cross_admin"
  ON tickets FOR SELECT TO authenticated
  USING (
    get_my_role() = 'developer'
    AND (
      company_id = get_my_company()
      OR company_id IN (
        SELECT client_company_id FROM client_companies
        WHERE admin_company_id = get_my_company()
      )
    )
  );

CREATE POLICY "tickets_developer_cross_admin_insert"
  ON tickets FOR INSERT TO authenticated
  WITH CHECK (
    get_my_role() = 'developer'
    AND (
      company_id = get_my_company()
      OR company_id IN (
        SELECT client_company_id FROM client_companies
        WHERE admin_company_id = get_my_company()
      )
    )
  );

CREATE POLICY "tickets_developer_cross_admin_update"
  ON tickets FOR UPDATE TO authenticated
  USING (
    get_my_role() = 'developer'
    AND (
      company_id = get_my_company()
      OR company_id IN (
        SELECT client_company_id FROM client_companies
        WHERE admin_company_id = get_my_company()
      )
    )
  )
  WITH CHECK (
    get_my_role() = 'developer'
    AND (
      company_id = get_my_company()
      OR company_id IN (
        SELECT client_company_id FROM client_companies
        WHERE admin_company_id = get_my_company()
      )
    )
  );

-- ============================================================
-- Helper function: Get admin's clients
-- ============================================================

CREATE OR REPLACE FUNCTION get_my_clients()
RETURNS TABLE (client_id uuid, client_name text)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT c.id, c.name
  FROM companies c
  INNER JOIN client_companies cc ON c.id = cc.client_company_id
  WHERE cc.admin_company_id = get_my_company()
  AND get_my_role() = 'admin';
$$;

-- ============================================================
-- Helper function: Get developer's accessible companies
-- ============================================================

CREATE OR REPLACE FUNCTION get_dev_accessible_companies()
RETURNS TABLE (company_id uuid)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT DISTINCT company_id FROM profiles WHERE id = auth.uid()
  UNION
  SELECT DISTINCT client_company_id FROM client_companies
  WHERE admin_company_id IN (
    SELECT get_my_company() WHERE get_my_role() = 'developer'
  );
$$;
